---
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    uses:
      freebased/github-workflows/.github/workflows/build.yml@master
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
